export * from "./paths.js";
export * from "./exec.js";
export * from "./windows-shim.js";
export * from "./git.js";
export * from "./command.js";
export * from "./store.js";
export * from "./identity.js";
export * from "./config.js";
export * from "./project.js";
export * from "./ports.js";
export * from "./capture.js";
export * from "./materialize.js";
export * from "./proof.js";
export * from "./rescue.js";
export * from "./promote.js";
export * from "./verify-local.js";
export * from "./companion.js";
export { defaultRegistry as defaultRegistryForCompanion } from "@iwomc/adapters";
export type { AdapterRegistry, MaterializationContext, ProjectFiles } from "@iwomc/adapters";
